[versions]
paper-server = "1.21.1"
paper-api = "1.21.1-R0.1-SNAPSHOT"

# https://hub.spigotmc.org/jenkins/job/BungeeCord/ws/api/target/apidocs/index.html
bungeecord="1.21-R0.5-SNAPSHOT"

# https://github.com/JetBrains/kotlin/releases
kotlin = "2.3.0"

# https://github.com/jpenilla/run-task/releases
runPaperTask = "3.0.2"

# https://github.com/GradleUp/shadow/releases
gradleupShadow = "9.2.2"

# https://github.com/PaperMC/adventure/releases
adventure = "4.17.0"
# https://github.com/PaperMC/adventure-platform/releases
adventure-bungeecord = "4.4.1"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
gradleupShadow = { id = "com.gradleup.shadow", version.ref = "gradleupShadow" }
runPaperTask = { id = "xyz.jpenilla.run-paper", version.ref = "runPaperTask" }

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
bungeecord-api = { module = "net.md-5:bungeecord-api", version.ref="bungeecord" }

kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }

adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure" }
adventure-bungeecord = { module = "net.kyori:adventure-platform-bungeecord", version.ref = "adventure-bungeecord" }